# Turns a binary file into a C array, at build time, with no tool beyond
# CMake itself:
#
#   cmake -DINPUT=file.bin -DOUTPUT=file.c -DSYMBOL=name -P tools/embed_bin.cmake
#
# Writes `const unsigned char name[]` and `const size_t name_size`. Used for
# patches/build/patches.bin (CMakeLists.txt); see patches/patch.ld for why
# those bytes have to reach memory.
if (NOT INPUT OR NOT OUTPUT OR NOT SYMBOL)
    message(FATAL_ERROR "embed_bin.cmake needs INPUT, OUTPUT and SYMBOL")
endif()
file(READ "${INPUT}" HEX_CONTENT HEX)
string(LENGTH "${HEX_CONTENT}" HEX_LENGTH)
math(EXPR BYTE_COUNT "${HEX_LENGTH} / 2")
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," ARRAY_BODY "${HEX_CONTENT}")
string(REGEX REPLACE "((0x[0-9a-f][0-9a-f],){16})" "\\1\n    " ARRAY_BODY "${ARRAY_BODY}")
file(WRITE "${OUTPUT}" "/* Generated by tools/embed_bin.cmake from ${INPUT}; do not edit. */
#include <stddef.h>
const unsigned char ${SYMBOL}[] = {
    ${ARRAY_BODY}
};
const size_t ${SYMBOL}_size = ${BYTE_COUNT};
")
