#!/usr/bin/env python3
"""Extract the menu's furniture glyphs from the original sprites.

Decodes the "Screen" label (VRAM 0x8033F498) for the items' bullet dot and
the "Stereo" value strip (VRAM 0x80342FF0) for the two big chevron
brackets, straight out of the menu's VPK0 segment. Emits:
  src/menu_dot.h        -- IA pairs for C++ (dot, bracket L, bracket R)
  tools/menu_glyphs.py  -- the same data for the reference generator

Run under WSL from the repo root:
  python3 tools/extract_menu_dot.py <rom>
"""
import os
import struct
import sys

sys.path.insert(0, os.path.expanduser("~/pokemonsnap/tools"))
from vpk0_codec import decompress_vpk0

ROM_VPK0 = 0xA0F830
VPK_VRAM = 0x802B5000
LABEL_VRAM = 0x8033F498    # "• Screen"
VALUE_VRAM = 0x80342FF0    # "< Stereo >"


def decode_sprite(seg, vram):
    off = lambda v: v - VPK_VRAM
    sp = off(vram)
    width, height = struct.unpack_from(">hh", seg, sp + 4)
    nbitmaps = struct.unpack_from(">h", seg, sp + 0x28)[0]
    bmHreal = struct.unpack_from(">h", seg, sp + 0x2E)[0]
    bitmap_ptr = struct.unpack_from(">I", seg, sp + 0x34)[0]

    img = [[(0, 0)] * width for _ in range(height)]
    x_cursor = 0
    for bi in range(nbitmaps):
        b = off(bitmap_ptr) + bi * 0x10
        bw, bw_img = struct.unpack_from(">hh", seg, b)
        buf = struct.unpack_from(">I", seg, b + 8)[0]
        rows = struct.unpack_from(">h", seg, b + 0xC)[0] or bmHreal
        rowbytes = bw_img * 2
        data = seg[off(buf): off(buf) + rowbytes * rows]
        for ry in range(min(rows, height)):
            row = bytearray(data[ry * rowbytes:(ry + 1) * rowbytes])
            if ry & 1:
                for i in range(0, rowbytes - 7, 8):
                    row[i:i+4], row[i+4:i+8] = row[i+4:i+8], row[i:i+4]
            for px in range(min(bw, width - x_cursor)):
                v = struct.unpack_from(">H", row, px * 2)[0]
                img[ry][x_cursor + px] = (v >> 8, v & 0xFF)
        x_cursor += bw
    return img, width, height


def col_core(img, width, height):
    return ["#" if any(img[y][x][1] >= 128 for y in range(height)) else "." for x in range(width)]


def crop(img, x0, x1, height):
    return [[img[y][x] for x in range(x0, x1)] for y in range(height)]


def main():
    rom_path = sys.argv[1]
    with open(rom_path, "rb") as f:
        f.seek(ROM_VPK0)
        comp = f.read(0xA5CC46 - ROM_VPK0)
    seg, _ = decompress_vpk0(comp)

    # Bullet dot: the run of solid columns before the label text.
    limg, lw, lh = decode_sprite(seg, LABEL_VRAM)
    core = col_core(limg, lw, lh)
    dot_end = core.index(".", core.index("#")) - 1
    text_start = dot_end + 1 + core[dot_end + 1:].index("#") - 1
    dot = crop(limg, 0, dot_end + 2, lh)
    print(f"dot cols 0..{dot_end + 1}, text starts {text_start}")

    # Brackets: first and last solid runs of the value strip.
    vimg, vw, vh = decode_sprite(seg, VALUE_VRAM)
    vcore = col_core(vimg, vw, vh)
    l_end = vcore.index(".", vcore.index("#")) - 1
    r_start = vw - 1 - vcore[::-1].index("#")
    while r_start > 0 and vcore[r_start - 1] == "#":
        r_start -= 1
    brk_l = crop(vimg, 0, l_end + 2, vh)
    brk_r = crop(vimg, max(0, r_start - 1), vw, vh)
    print(f"bracket L cols 0..{l_end + 1}, bracket R cols {r_start - 1}..{vw - 1}")

    def emit_c(f, name, block):
        h, w = len(block), len(block[0])
        f.write(f"constexpr int k{name}W = {w};\n")
        f.write(f"constexpr int k{name}H = {h};\n")
        f.write(f"constexpr unsigned char k{name}IA[] = {{\n")
        for row in block:
            f.write("    " + " ".join(f"0x{i:02X},0x{a:02X}," for i, a in row) + "\n")
        f.write("};\n")

    with open("src/menu_dot.h", "w") as f:
        f.write("// The Option menu's furniture, decoded from the original sprites:\n")
        f.write("// the items' bullet dot (\"Screen\" label, VRAM 0x8033F498) and the\n")
        f.write("// value chevrons (\"Stereo\" strip, VRAM 0x80342FF0), IA pairs,\n")
        f.write("// row-major. Generated by tools/extract_menu_dot.py.\n")
        f.write(f"constexpr int kMenuDotTextStart = {text_start};\n")
        emit_c(f, "MenuDot", dot)
        emit_c(f, "MenuBrkL", brk_l)
        emit_c(f, "MenuBrkR", brk_r)
    print("wrote src/menu_dot.h")

    with open("tools/menu_glyphs.py", "w") as f:
        f.write("# Generated by tools/extract_menu_dot.py -- see src/menu_dot.h.\n")
        f.write(f"TEXT_START = {text_start}\n")
        f.write(f"DOT = {dot!r}\n")
        f.write(f"BRK_L = {brk_l!r}\n")
        f.write(f"BRK_R = {brk_r!r}\n")
    print("wrote tools/menu_glyphs.py")


if __name__ == "__main__":
    main()
