"""The game's functions as absolute linker symbols, for the patch bytes.

The patches' calls into the game are left unresolved in build/patches.elf
on purpose: the recompiler matches each one's relocation to a game function
(patches/Makefile). The same link made build/patches.bin, the bytes the
runtime copies into memory and reads when a mod hooks a function the
patches replace: it recompiles that function live from these bytes. There
every call into the game and every address of a game function (a process
handed to omCreateProcess) was zero, and the live code called address 0.
The Makefile links the patch objects a second time with this script, which
defines each function in patches/pokemonsnap.syms.toml at its address
(PROVIDE: a function the patches define themselves keeps their definition),
and the bytes come from that link.

Usage: python3 tools/gen_patch_funcs_ld.py patches/pokemonsnap.syms.toml build/game_funcs.ld
"""
import re
import sys


def main() -> int:
    syms_path, out_path = sys.argv[1], sys.argv[2]
    with open(syms_path, encoding='utf-8') as f:
        text = f.read()
    funcs = {}
    for name, vram in re.findall(r'\{\s*name = "([^"]+)", vram = (0x[0-9A-Fa-f]+)', text):
        address = int(vram, 16)
        assert funcs.get(name, address) == address, f'{name} is listed at two addresses'
        funcs[name] = address
    assert funcs, f'no functions in {syms_path}'
    with open(out_path, 'w', encoding='utf-8', newline='\n') as f:
        f.write('/* Generated by tools/gen_patch_funcs_ld.py from %s -- do not edit. */\n' % syms_path)
        for name in sorted(funcs):
            f.write('PROVIDE(%s = 0x%08X);\n' % (name, funcs[name]))
    print(f'{out_path}: {len(funcs)} game functions')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
