"""Rasterise the Snap Station printer's on-screen lettering into bitmaps.

The kiosk's video printer drew "PRINTING..." and "PLEASE WAIT" over its
sixteen-picture grid in a condensed grotesque: capitals thirty-six lines
tall and about sixteen wide, stems four wide and bars three, letters
centred on a twenty-three pixel pitch. The printer's own character set is
not recoverable from photographs of a curved screen, so this takes a
freely licensed grotesque of the same construction -- Roboto Regular
(Apache License 2.0, https://github.com/googlefonts/roboto) -- and sets
each capital the printer's way: scaled to the cap height, condensed to the
cell, thresholded, and thickened one pixel to the right so a stem is four
pixels. What ships is the resulting bitmaps in src/snap_station_osd_font.h;
no font software is embedded.

    python tools/osd_font_gen.py path/to/Roboto-Regular.ttf

Writes src/snap_station_osd_font.h and, beside the font file, a sheet of
the letters for checking against the photographs.
"""
import os
import sys

from PIL import Image, ImageDraw, ImageFont

LETTERS = "PRINTGLEASW"
ROWS = 36        # cap height
COLS = 18        # the cell the glyph is centred in; bit 0 is the left column
MAX_WIDTH = 15   # a capital no wider than this before the bold (W may use 17)
THRESHOLD = 118
BOLD_RIGHT = 1   # pixels added to the right of every ink pixel


def serifed_i():
    """The printer's I is not a bare stroke: a three-pixel stem with a short
    bar at top and bottom, nine wide and three tall, centred like the other
    capitals. Set by hand; Roboto's I is a plain stroke."""
    rows = []
    left = (MAX_WIDTH - 9) // 2
    for y in range(ROWS):
        if y < 3 or y >= ROWS - 3:
            bits = sum(1 << x for x in range(left, left + 9))
        else:
            bits = sum(1 << x for x in range(left + 3, left + 6))
        rows.append(bits)
    return rows


def rasterise(font_path, letter):
    if letter == "I":
        return serifed_i()
    font = ImageFont.truetype(font_path, 240)
    canvas = Image.new("L", (600, 600), 0)
    ImageDraw.Draw(canvas).text((80, 80), letter, font=font, fill=255)
    glyph = canvas.crop(canvas.getbbox())
    scale = ROWS / glyph.height
    width = max(1, round(glyph.width * scale))
    limit = 17 if letter == "W" else MAX_WIDTH
    width = min(width, limit)
    glyph = glyph.resize((width, ROWS), Image.LANCZOS)
    cell = Image.new("L", (COLS, ROWS), 0)
    cell.paste(glyph, ((limit - width) // 2, 0))
    ink = cell.point(lambda v: 255 if v > THRESHOLD else 0)
    px = ink.load()
    for y in range(ROWS):
        for x in range(COLS - 1, 0, -1):
            if px[x - 1, y] == 255 and BOLD_RIGHT:
                px[x, y] = 255
    rows = []
    for y in range(ROWS):
        bits = 0
        for x in range(COLS):
            if px[x, y] == 255:
                bits |= 1 << x
        rows.append(bits)
    return rows


def main():
    if len(sys.argv) != 2:
        print(__doc__)
        return 2
    font_path = sys.argv[1]
    here = os.path.dirname(os.path.abspath(__file__))
    out = os.path.join(here, "..", "src", "snap_station_osd_font.h")
    glyphs = {letter: rasterise(font_path, letter) for letter in LETTERS}

    lines = []
    lines.append("// Generated by tools/osd_font_gen.py from Roboto Regular (Apache License")
    lines.append("// 2.0): the Snap Station printer's lettering as bitmaps, thirty-six rows")
    lines.append("// of eighteen columns, bit 0 the left column. Do not edit; rerun the tool.")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <cstdint>")
    lines.append("")
    lines.append("namespace snap_osd {")
    lines.append(f"constexpr int GlyphRows = {ROWS};")
    lines.append(f"constexpr int GlyphCols = {COLS};")
    lines.append("struct Glyph {")
    lines.append("    char ch;")
    lines.append("    uint32_t rows[GlyphRows];")
    lines.append("};")
    lines.append("constexpr Glyph kGlyphs[] = {")
    for letter in LETTERS:
        rows = glyphs[letter]
        lines.append(f"    {{ '{letter}', {{")
        for i in range(0, ROWS, 6):
            lines.append("        " + ", ".join(f"0x{v:05X}" for v in rows[i:i + 6]) + ",")
        lines.append("    } },")
    lines.append("};")
    lines.append("}  // namespace snap_osd")
    lines.append("")
    with open(out, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    print("wrote", os.path.normpath(out))

    # A sheet of the letters, six times their size, for checking by eye.
    sheet = Image.new("RGB", (len(LETTERS) * 23 * 6, ROWS * 6 + 24), (0, 60, 160))
    for i, letter in enumerate(LETTERS):
        for y, bits in enumerate(glyphs[letter]):
            for x in range(COLS):
                if (bits >> x) & 1:
                    sheet.paste((255, 255, 255), ((i * 23 + x) * 6, (y + 2) * 6, (i * 23 + x + 1) * 6, (y + 3) * 6))
    sheet_path = os.path.join(os.path.dirname(os.path.abspath(font_path)), "osd_font_sheet.png")
    sheet.save(sheet_path)
    print("wrote", sheet_path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
