# Copies the recompiled patches into the build tree as plain C for every
# compiler, at build time, with no tool beyond CMake:
#
#   cmake -DINPUT_DIR=RecompiledPatches -DOUTPUT_DIR=<build>/generated/patches -P tools/portable_patches.cmake
#
# Two things the recompiler's output leaves to the host compiler's leniency:
#
# * The game is recompiled with __sinf and __cosf emitted as __sinf_recomp
#   and __cosf_recomp (N64Recomp renames functions that collide with the C
#   library). The patches are recompiled separately, resolve those two
#   through the reference symbols, and call them by their plain names. On
#   MSVC the plain names are free and were bridged by a shim; glibc's math.h
#   declares float __sinf(float) and float __cosf(float) in every translation
#   unit that includes recomp.h, so on Linux the plain names cannot be
#   defined or called with the recompiler's two arguments at all. The copy
#   calls the game's real names directly; the shim is gone.
# * Every game function the patches call is left undeclared (the calls
#   resolve at link time against the recompiled game). MSVC and GCC accept
#   the implicit declarations; Clang 16 and later reject them. A prototype
#   is prepended for each distinct callee the file does not define itself
#   (its own functions are declared by its funcs.h, with RECOMP_FUNC's
#   modifiers, which a plain prototype would contradict).
if (NOT INPUT_DIR OR NOT OUTPUT_DIR)
    message(FATAL_ERROR "portable_patches.cmake needs INPUT_DIR and OUTPUT_DIR")
endif()
file(MAKE_DIRECTORY "${OUTPUT_DIR}")
file(READ "${INPUT_DIR}/patches.c" CONTENT)
string(REPLACE "__sinf(rdram, ctx)" "__sinf_recomp(rdram, ctx)" CONTENT "${CONTENT}")
string(REPLACE "__cosf(rdram, ctx)" "__cosf_recomp(rdram, ctx)" CONTENT "${CONTENT}")

# The callees: every indented "name(rdram, ctx)" call. The match stops
# before the semicolon on purpose: a semicolon inside a CMake list element
# would split it.
string(REGEX MATCHALL "\n +[A-Za-z_][A-Za-z0-9_]*\\(rdram, ctx\\)" CALLS "${CONTENT}")
set(CALLEES "")
foreach(_call IN LISTS CALLS)
    string(REGEX REPLACE "^\n +([A-Za-z_][A-Za-z0-9_]*)\\(rdram, ctx\\)$" "\\1" _name "${_call}")
    string(FIND "${CONTENT}" "RECOMP_FUNC void ${_name}(" _defined)
    if (_defined EQUAL -1)
        list(APPEND CALLEES "${_name}")
    endif()
endforeach()
list(REMOVE_DUPLICATES CALLEES)
list(SORT CALLEES)
set(PROTOTYPES "/* tools/portable_patches.cmake: every game function the patches call, the libultra sines by the game's own names. */\n")
foreach(_name IN LISTS CALLEES)
    string(APPEND PROTOTYPES "void ${_name}(uint8_t* rdram, recomp_context* ctx);\n")
endforeach()
string(REPLACE "#include \"funcs.h\"\n" "#include \"funcs.h\"\n${PROTOTYPES}" CONTENT "${CONTENT}")

file(WRITE "${OUTPUT_DIR}/patches.c" "/* Generated by tools/portable_patches.cmake from ${INPUT_DIR}/patches.c; do not edit. */\n${CONTENT}")
foreach(_h funcs.h recomp_overlays.inl)
    if (EXISTS "${INPUT_DIR}/${_h}")
        configure_file("${INPUT_DIR}/${_h}" "${OUTPUT_DIR}/${_h}" COPYONLY)
    endif()
endforeach()
