# Copies the recompiled patches into the build tree with the two libultra
# names glibc reserves renamed, at build time, with no tool beyond CMake:
#
#   cmake -DINPUT_DIR=RecompiledPatches -DOUTPUT_DIR=<build>/generated/patches -P tools/portable_patches.cmake
#
# The game is recompiled with __sinf and __cosf emitted as __sinf_recomp and
# __cosf_recomp (N64Recomp renames functions that collide with the C
# library). The patches are recompiled separately, resolve those two through
# the reference symbols, and call them by their plain names. On MSVC the
# plain names are free and were bridged by a shim; glibc's math.h declares
# float __sinf(float) and float __cosf(float) in every translation unit that
# includes recomp.h, so on Linux the plain names cannot be defined or called
# with the recompiler's two arguments at all. The copy compiled on every
# platform calls the game's real names directly; the shim is gone.
if (NOT INPUT_DIR OR NOT OUTPUT_DIR)
    message(FATAL_ERROR "portable_patches.cmake needs INPUT_DIR and OUTPUT_DIR")
endif()
file(MAKE_DIRECTORY "${OUTPUT_DIR}")
file(READ "${INPUT_DIR}/patches.c" CONTENT)
string(REPLACE "__sinf(rdram, ctx)" "__sinf_recomp(rdram, ctx)" CONTENT "${CONTENT}")
string(REPLACE "__cosf(rdram, ctx)" "__cosf_recomp(rdram, ctx)" CONTENT "${CONTENT}")
string(REPLACE "#include \"funcs.h\"\n" "#include \"funcs.h\"\n/* tools/portable_patches.cmake: the game's names for libultra's __sinf and __cosf. */\nvoid __sinf_recomp(uint8_t* rdram, recomp_context* ctx);\nvoid __cosf_recomp(uint8_t* rdram, recomp_context* ctx);\n" CONTENT "${CONTENT}")
file(WRITE "${OUTPUT_DIR}/patches.c" "/* Generated by tools/portable_patches.cmake from ${INPUT_DIR}/patches.c; do not edit. */\n${CONTENT}")
foreach(_h funcs.h recomp_overlays.inl)
    if (EXISTS "${INPUT_DIR}/${_h}")
        configure_file("${INPUT_DIR}/${_h}" "${OUTPUT_DIR}/${_h}" COPYONLY)
    endif()
endforeach()
