/**
 * @file menu_assets.cpp
 * @brief Stages the GRAPHICS menu's text and carries its settings mailbox.
 *
 * The in-game GRAPHICS page (patches/src/graphics_menu_patch.c) draws with
 * the game's own UI font, but the font's code lives in the window overlay,
 * which the main menu unloads -- so the glyphs have to arrive as pixels, not
 * as calls. This file reads the font straight out of the ROM -- the same
 * 4-bit atlas the game's photo-review interface draws with -- composites
 * every string the page needs into an IA16 strip with the interface's own
 * two-pixel drop shadow, and writes the strips into otherwise-unused RDRAM
 * where the patch wraps them in sprites.
 *
 * Settings cross the same boundary through a 16-byte mailbox: this side
 * seeds it with the saved values, the page edits bytes and bumps a sequence
 * counter, and the poll below applies and persists on each bump -- so every
 * change takes effect while the menu is still open, through exactly the same
 * path the hotkeys use.
 *
 * All RDRAM writes go through the recompiler's addressing (words direct,
 * halves XOR 2, bytes XOR 3), which also matches what a DMA from ROM would
 * have produced -- the RDP reads these strips exactly as it reads any other
 * texture the game loaded.
 */
#include <algorithm>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <string>
#include <vector>

#include "settings.h"

// stb_image's implementation is compiled inside the RT64 library
// (rt64_texture_cache.cpp); this include only brings the declarations.
#include "stb/stb_image.h"

// The Options items' bullet dot and the value chevrons, decoded from the
// original menu sprites. Generated by tools/extract_menu_dot.py.
#include "menu_dot.h"
// The menu sprite font itself: letterforms harvested from the original
// pre-rendered sprites. Generated by tools/harvest_menu_font.py.
#include "menu_font.h"

namespace snap {

namespace {

constexpr uint32_t MailboxAddr = 0x80C00000u;
constexpr uint32_t DirectoryAddr = 0x80C01000u;
constexpr uint32_t PixelsAddr = 0x80C01100u;
constexpr uint32_t MailboxMagic = 0x53474658u;   // 'SGFX'
constexpr uint32_t DirectoryMagic = 0x53474130u; // 'SGA0'
constexpr uint32_t STR_ITEM_LABEL_ID = 1;        // "Graphics", the Option item

// The strips are exactly as tall as the original menu sprites: ten rows.
constexpr int StripHeight = kMenuFontCellH;

struct Strip {
    int width = 0;
    int height = StripHeight;
    std::vector<uint8_t> intensity;  // width * height
    std::vector<uint8_t> alpha;
};

uint8_t* g_menu_rdram = nullptr;

void write_u32(uint32_t addr, uint32_t v) {
    *reinterpret_cast<uint32_t*>(g_menu_rdram + (addr - 0x80000000u)) = v;
}

uint32_t read_u32_mail(uint32_t addr) {
    return *reinterpret_cast<uint32_t*>(g_menu_rdram + (addr - 0x80000000u));
}

void write_u16(uint32_t addr, uint16_t v) {
    *reinterpret_cast<uint16_t*>(g_menu_rdram + ((addr ^ 2u) - 0x80000000u)) = v;
}

void write_u8(uint32_t addr, uint8_t v) {
    g_menu_rdram[(addr ^ 3u) - 0x80000000u] = v;
}

uint8_t read_u8_mail(uint32_t addr) {
    return g_menu_rdram[(addr ^ 3u) - 0x80000000u];
}

const MenuGlyph* menu_glyph(char c) {
    for (size_t i = 0; i < sizeof(kMenuFontGlyphs) / sizeof(kMenuFontGlyphs[0]); i++) {
        if (kMenuFontGlyphs[i].ch == c) {
            return &kMenuFontGlyphs[i];
        }
    }
    return nullptr;
}

// Composites a string from the menu sprite font: the original letterforms,
// each cell blitted as decoded (no synthetic shadow -- the originals bake
// none), advanced by ink width plus the gap measured from the original
// layouts. The cursor tracks ink columns; each cell carries one column of
// antialiasing fringe on either side.
Strip compose(const char* text) {
    Strip strip;

    int xc = 1;
    for (const char* c = text; *c != 0; c++) {
        if (*c == ' ') {
            xc += kMenuFontSpaceGap;
        }
        else if (*c == '<') {
            xc += kMenuBrkLW - 2;
        }
        else if (*c == '>') {
            xc += kMenuBrkRW - 2;
        }
        else if (const MenuGlyph* g = menu_glyph(*c)) {
            xc += g->coreW + kMenuFontLetterGap;
        }
        else {
            xc += 6;
        }
    }

    // Rounded up to whole 64-texel blocks: each block is loaded with a
    // single block load, and the loader's odd-row swap only lines up when a
    // row is a multiple of eight bytes. A narrower final block shears into
    // diagonals -- measured on screen before this rounding existed.
    int width = (xc + 2 + 63) & ~63;

    strip.width = width;
    strip.intensity.assign(size_t(width) * StripHeight, 0);
    strip.alpha.assign(size_t(width) * StripHeight, 0);

    auto blend = [&](int px, int py, uint8_t i, uint8_t a) {
        if ((px < 0) || (px >= width) || (py < 0) || (py >= StripHeight) || (a == 0)) {
            return;
        }
        const size_t at = size_t(py) * width + px;
        if (a >= strip.alpha[at]) {
            strip.intensity[at] = std::max(strip.intensity[at], i);
            strip.alpha[at] = a;
        }
    };

    xc = 1;
    for (const char* c = text; *c != 0; c++) {
        if (*c == ' ') {
            xc += kMenuFontSpaceGap;
            continue;
        }
        if ((*c == '<') || (*c == '>')) {
            // The original chevrons, as decoded pixels.
            const bool left = (*c == '<');
            const int bw = left ? kMenuBrkLW : kMenuBrkRW;
            const int bh = left ? kMenuBrkLH : kMenuBrkRH;
            const unsigned char* ia = left ? kMenuBrkLIA : kMenuBrkRIA;
            for (int gy = 0; (gy < bh) && (gy < StripHeight); gy++) {
                for (int gx = 0; gx < bw; gx++) {
                    blend(xc - 1 + gx, gy, ia[(gy * bw + gx) * 2 + 0], ia[(gy * bw + gx) * 2 + 1]);
                }
            }
            xc += bw - 2;
            continue;
        }
        const MenuGlyph* g = menu_glyph(*c);
        if (g == nullptr) {
            xc += 6;
            continue;
        }
        const unsigned char* ia = kMenuFontIA + size_t(g->off) * 2;
        for (int gy = 0; gy < kMenuFontCellH; gy++) {
            for (int gx = 0; gx < g->cellW; gx++) {
                blend(xc - g->coreStart + gx, gy,
                      ia[(gy * g->cellW + gx) * 2 + 0], ia[(gy * g->cellW + gx) * 2 + 1]);
            }
        }
        xc += g->coreW + kMenuFontLetterGap;
    }

    return strip;
}

// One line in the header face -- the medium font of the Options screen's
// own title sprite, for the page's "Graphics" heading.
Strip compose_hdr(const char* text) {
    Strip strip;
    strip.height = kMenuHdrCellH;

    auto hdr_glyph = [](char c) -> const MenuGlyph* {
        for (size_t i = 0; i < sizeof(kMenuHdrGlyphs) / sizeof(kMenuHdrGlyphs[0]); i++) {
            if (kMenuHdrGlyphs[i].ch == c) {
                return &kMenuHdrGlyphs[i];
            }
        }
        return nullptr;
    };

    int xc = 1;
    for (const char* c = text; *c != 0; c++) {
        if (*c == ' ') {
            xc += kMenuFontSpaceGap + 2;
        }
        else if (const MenuGlyph* g = hdr_glyph(*c)) {
            xc += g->coreW + kMenuFontLetterGap;
        }
    }
    strip.width = (xc + 2 + 63) & ~63;
    strip.intensity.assign(size_t(strip.width) * strip.height, 0);
    strip.alpha.assign(size_t(strip.width) * strip.height, 0);

    xc = 1;
    for (const char* c = text; *c != 0; c++) {
        if (*c == ' ') {
            xc += kMenuFontSpaceGap + 2;
            continue;
        }
        const MenuGlyph* g = hdr_glyph(*c);
        if (g == nullptr) {
            continue;
        }
        const unsigned char* ia = kMenuHdrIA + size_t(g->off) * 2;
        for (int gy = 0; gy < kMenuHdrCellH; gy++) {
            for (int gx = 0; gx < g->cellW; gx++) {
                const int px = xc - g->coreStart + gx;
                if ((px < 0) || (px >= strip.width)) {
                    continue;
                }
                const uint8_t i = ia[(gy * g->cellW + gx) * 2 + 0];
                const uint8_t a = ia[(gy * g->cellW + gx) * 2 + 1];
                const size_t at = size_t(gy) * strip.width + px;
                if ((a != 0) && (a >= strip.alpha[at])) {
                    strip.intensity[at] = std::max(strip.intensity[at], i);
                    strip.alpha[at] = a;
                }
            }
        }
        xc += g->coreW + kMenuFontLetterGap;
    }
    return strip;
}

// Two body-face lines stacked at the stock help sprites' own line pitch of
// twelve rows -- the settings descriptions in the help box.
Strip compose_lines(const char* line1, const char* line2) {
    Strip a = compose(line1);
    Strip b = compose(line2);
    Strip out;
    out.height = 12 + StripHeight;
    out.width = std::max(a.width, b.width);
    out.intensity.assign(size_t(out.width) * out.height, 0);
    out.alpha.assign(size_t(out.width) * out.height, 0);
    for (int y = 0; y < StripHeight; y++) {
        for (int x = 0; x < a.width; x++) {
            out.intensity[size_t(y) * out.width + x] = a.intensity[size_t(y) * a.width + x];
            out.alpha[size_t(y) * out.width + x] = a.alpha[size_t(y) * a.width + x];
        }
        for (int x = 0; x < b.width; x++) {
            out.intensity[size_t(y + 12) * out.width + x] = b.intensity[size_t(y) * b.width + x];
            out.alpha[size_t(y + 12) * out.width + x] = b.alpha[size_t(y) * b.width + x];
        }
    }
    return out;
}

// Prepends the original bullet dot to a composed label strip, at the same
// spacing the stock Option items use: dot pixels first, the text starting
// at the column the original "Screen" label starts its S.
Strip add_item_dot(const Strip &text) {
    Strip out;
    out.width = (kMenuDotTextStart + text.width + 63) & ~63;
    out.intensity.assign(size_t(out.width) * StripHeight, 0);
    out.alpha.assign(size_t(out.width) * StripHeight, 0);
    for (int y = 0; y < StripHeight; y++) {
        for (int x = 0; x < text.width; x++) {
            out.intensity[size_t(y) * out.width + kMenuDotTextStart + x] = text.intensity[size_t(y) * text.width + x];
            out.alpha[size_t(y) * out.width + kMenuDotTextStart + x] = text.alpha[size_t(y) * text.width + x];
        }
    }
    for (int y = 0; y < kMenuDotH && y < StripHeight; y++) {
        for (int x = 0; x < kMenuDotW; x++) {
            const uint8_t di = kMenuDotIA[(y * kMenuDotW + x) * 2 + 0];
            const uint8_t da = kMenuDotIA[(y * kMenuDotW + x) * 2 + 1];
            if (da != 0) {
                out.intensity[size_t(y) * out.width + x] = di;
                out.alpha[size_t(y) * out.width + x] = da;
            }
        }
    }
    return out;
}

// The interface's thin +1,+1 drop shadow, rebuilt from a strip's alpha mask
// exactly the way compose() lays it under the glyphs. Used for overrides
// whose source image had no transparency, where any authored shadow was
// indistinguishable from the background and lost in conversion.
void apply_shadow(Strip &strip) {
    const std::vector<uint8_t> srcI = strip.intensity;
    const std::vector<uint8_t> srcA = strip.alpha;
    std::fill(strip.intensity.begin(), strip.intensity.end(), 0);
    std::fill(strip.alpha.begin(), strip.alpha.end(), 0);

    auto blend = [&](int px, int py, uint8_t i, uint8_t a) {
        if ((px < 0) || (px >= strip.width) || (py < 0) || (py >= StripHeight) || (a == 0)) {
            return;
        }
        const size_t at = size_t(py) * strip.width + px;
        if (a >= strip.alpha[at]) {
            strip.intensity[at] = std::max(strip.intensity[at], i);
            strip.alpha[at] = a;
        }
    };

    for (int pass = 0; pass < 2; pass++) {
        for (int y = 0; y < StripHeight; y++) {
            for (int x = 0; x < strip.width; x++) {
                const size_t at = size_t(y) * strip.width + x;
                if (srcA[at] == 0) {
                    continue;
                }
                if (pass == 0) {
                    blend(x + 1, y + 1, 0, srcA[at]);
                }
                else {
                    blend(x, y, srcI[at], srcA[at]);
                }
            }
        }
    }
}

// A hand-made replacement for one string: menu_text/<name>.png next to the
// executable. Any resolution; downscaled to the strip height with a box
// filter. A transparent background is ideal (alpha carried through,
// luminance becoming the glyph intensity), but a fully opaque image --
// image generators love white-on-black -- converts automatically: luminance
// becomes the alpha, the glyphs read as white, and the interface's drop
// shadow is rebuilt underneath. Missing or unreadable files simply fall
// back to the font renderer, so partial sets are fine.
bool load_override(const char* name, Strip &strip) {
    char path[256];
    snprintf(path, sizeof(path), "menu_text/%s.png", name);
    int w = 0, h = 0, comp = 0;
    stbi_uc* data = stbi_load(path, &w, &h, &comp, 4);
    if (data == nullptr) {
        return false;
    }
    if ((w <= 0) || (h <= 0)) {
        stbi_image_free(data);
        return false;
    }

    // A fully opaque image can carry no transparency information: treat its
    // luminance as the alpha channel instead, so white-on-black renders as
    // white-on-transparent.
    bool opaque = true;
    for (int i = 0; i < w * h; i++) {
        if (data[size_t(i) * 4 + 3] < 250) {
            opaque = false;
            break;
        }
    }

    // Scale to the strip height, preserving aspect.
    const double scale = double(StripHeight) / double(h);
    int outW = std::max(1, int(w * scale + 0.5));
    outW = (outW + 63) & ~63;
    strip.width = outW;
    strip.intensity.assign(size_t(outW) * StripHeight, 0);
    strip.alpha.assign(size_t(outW) * StripHeight, 0);

    for (int y = 0; y < StripHeight; y++) {
        const int sy0 = int(y / scale);
        const int sy1 = std::min(h, std::max(sy0 + 1, int((y + 1) / scale)));
        for (int x = 0; x < int(w * scale + 0.5) && x < outW; x++) {
            const int sx0 = int(x / scale);
            const int sx1 = std::min(w, std::max(sx0 + 1, int((x + 1) / scale)));
            uint32_t sumL = 0, sumA = 0, n = 0;
            for (int sy = sy0; sy < sy1; sy++) {
                for (int sx = sx0; sx < sx1; sx++) {
                    const stbi_uc* px = data + (size_t(sy) * w + sx) * 4;
                    const uint32_t lum = (px[0] * 54 + px[1] * 183 + px[2] * 19) >> 8;
                    const uint32_t i = opaque ? 255u : lum;
                    const uint32_t a = opaque ? lum : px[3];
                    sumL += i * a / 255;
                    sumA += a;
                    n++;
                }
            }
            if (n > 0) {
                const size_t at = size_t(y) * outW + x;
                strip.intensity[at] = uint8_t(sumL / n);
                strip.alpha[at] = uint8_t(sumA / n);
            }
        }
    }

    stbi_image_free(data);
    if (opaque) {
        apply_shadow(strip);
    }
    return true;
}

uint32_t g_last_applied_seq = 0;
bool g_staged = false;

void seed_mailbox() {
    const Settings &s = settings();
    write_u8(MailboxAddr + 0x8, uint8_t(s.resolution_scale));
    const uint8_t msaaIndex = (s.msaa >= 8) ? 3 : (s.msaa >= 4) ? 2 : (s.msaa >= 2) ? 1 : 0;
    write_u8(MailboxAddr + 0x9, msaaIndex);
    write_u8(MailboxAddr + 0xA, s.widescreen ? 1 : 0);
    write_u8(MailboxAddr + 0xB, (s.fps_mode != 0) ? 1 : 0);
    write_u8(MailboxAddr + 0xC, uint8_t(s.upscale_2d));
    write_u8(MailboxAddr + 0xD, uint8_t(s.present_filter));
    write_u8(MailboxAddr + 0xE, s.dither_noise ? 1 : 0);
    write_u8(MailboxAddr + 0xF, s.fullscreen ? 1 : 0);
    write_u8(MailboxAddr + 0x10, uint8_t(std::clamp(s.downsample, 1, 4) - 1));
    write_u8(MailboxAddr + 0x11, s.three_point_filtering ? 0 : 1);
    write_u8(MailboxAddr + 0x12, uint8_t(std::clamp(s.color_depth, 0, 2)));
    write_u8(MailboxAddr + 0x13, s.triple_buffering ? 1 : 0);
    write_u32(MailboxAddr + 0x4, 0);
    write_u32(MailboxAddr + 0x0, MailboxMagic);
    g_last_applied_seq = 0;
}

} // namespace

// Composites and stages every string the GRAPHICS page draws. Idempotent;
// runs once, the first time an overlay load hands us RDRAM.
void stage_menu_assets(uint8_t* rdram) {
    if (rdram == nullptr) {
        return;
    }
    g_menu_rdram = rdram;

    if (g_staged) {
        // The menu cannot be open during an overlay load, so this is a safe
        // moment to refresh the mailbox with whatever the hotkeys changed.
        seed_mailbox();
        return;
    }


    const char* strings[] = {
        "",                                    // 0: 16x16 black tile (unused by the page now)
        "Graphics",                            // 1: the new Option item's label
        "Render Scale",                        // 2
        "Anti-Aliasing",                       // 3
        "Widescreen",                          // 4
        "Frame Rate",                          // 5
        "2D Detail",                           // 6
        "Filter",                              // 7
        "Dither",                              // 8
        "Fullscreen",                          // 9
        "Display and renderer settings.",      // 10: help line for the item
        "< Auto >",                            // 11
        "< Off >",                             // 12
        "< On >",                              // 13
        "< 1x >", "< 2x >", "< 3x >", "< 4x >",    // 14..17
        "< 5x >", "< 6x >", "< 7x >", "< 8x >",    // 18..21
        "< Original >",                        // 22
        "< Display >",                         // 23
        "< Classic >",                         // 24
        "< Sharp >",                           // 25
        "< Point >",                           // 26
        "< Smooth >",                          // 27
        "< Crisp >",                           // 28
        "Left and Right change the setting.",  // 29: kept for PNG-override compatibility
    };
    constexpr uint32_t BaseCount = uint32_t(sizeof(strings) / sizeof(strings[0]));

    // What each page row does, two lines apiece -- swapped into the help box
    // as the selection moves, the way the stock screen's helps follow it.
    // Ids BaseCount..BaseCount+7.
    static const char* const descs[8][2] = {
        { "Sets the 3D rendering resolution.",         "Auto follows the window size." },
        { "Smooths jagged edges on 3D models.",        "Higher levels cost more performance." },
        { "Widens the view for widescreen displays.",  "The picture stays undistorted." },
        { "Original keeps the native frame pace.",     "Display interpolates to your monitor." },
        { "Classic keeps 2D art at its original size.","Sharp redraws it at high resolution." },
        { "How the picture is scaled to the window.",  "Crisp keeps pixels sharp and smooth." },
        { "The original console dither pattern.",      "Adds fine noise to smooth gradients." },
        { "Switches between fullscreen and window.",   "" },
    };
    // Id BaseCount+22: the "Recomp" wordmark drawn under the Snap logo on
    // the title screen -- the port's one badge. Full colour, RGBA16, loaded
    // from menu_text/recomp_logo.png; absent file, absent badge.
    // Id BaseCount+8: the page's heading, in the Options title's own face.
    // Ids BaseCount+9..BaseCount+17: the second wave of settings -- labels
    // and values for the rows added when the page grew past the original
    // eight. Ids BaseCount+18..BaseCount+21: their descriptions.
    static const char* const extraStrings[9] = {
        "Super Sampling",                      // +9
        "Texture Filter",                      // +10
        "Color Depth",                         // +11
        "Buffering",                           // +12
        "< Authentic >",                       // +13
        "< Standard >",                        // +14
        "< High >",                            // +15
        "< Double >",                          // +16
        "< Triple >",                          // +17
    };
    static const char* const extraDescs[4][2] = {
        { "Renders above native and downsamples.",   "The cleanest image, at a heavy cost." },
        { "Authentic keeps the N64 three point look.","Smooth uses standard bilinear filtering." },
        { "High reduces banding in gradients.",      "Takes effect after restarting the game." },
        { "Triple buffering smooths frame delivery.","Takes effect after restarting the game." },
    };
    constexpr uint32_t StringCount = BaseCount + 23;

    const char* overrideNames[] = {
        nullptr, "graphics", "render_scale", "anti_aliasing", "widescreen",
        "frame_rate", "2d_detail", "filter", "dither", "fullscreen",
        "item_help", "auto", "off", "on",
        "1x", "2x", "3x", "4x", "5x", "6x", "7x", "8x",
        "original", "display", "classic", "sharp", "point", "smooth", "crisp",
        "page_help",
    };

    // The wordmark: any resolution, box-scaled to 128 texels wide (two
    // chunks), colours un-premultiplied back out of the average so edges
    // keep their hue, alpha cut at half for RGBA16's single bit.
    struct { int w = 0, h = 0; std::vector<uint16_t> texels; } logo;
    {
        int lw = 0, lh = 0, comp = 0;
        stbi_uc* data = stbi_load("menu_text/recomp_logo.png", &lw, &lh, &comp, 4);
        if ((data != nullptr) && (lw > 0) && (lh > 0)) {
            // Image generators fight transparency: a fully opaque image is
            // treated as white-backgrounded, and near-white pixels become
            // the transparency. The wordmark's own colours are saturated,
            // so nothing of it gets keyed away.
            bool opaqueImg = true;
            for (int i = 0; i < lw * lh; i++) {
                if (data[size_t(i) * 4 + 3] < 250) {
                    opaqueImg = false;
                    break;
                }
            }
            if (opaqueImg) {
                for (int i = 0; i < lw * lh; i++) {
                    stbi_uc* px = data + size_t(i) * 4;
                    const int whiteness = std::min(px[0], std::min(px[1], px[2]));
                    if (whiteness >= 240) {
                        px[3] = 0;
                    }
                }
            }
            // Drawn size versus staged size: a 64-texel 16-bit chunk row can
            // carry at most 32 rows through a block load (2048 texels of
            // TMEM), so the visible mark scales to 92 wide -- proportioned
            // under the Snap logo -- inside a two-chunk buffer whose spare
            // columns stay transparent.
            const int visW = 92;
            const int visH = std::clamp(int(double(lh) * visW / lw + 0.5), 8, 32);
            const int outW = 128;
            logo.w = outW;
            logo.h = visH;
            logo.texels.assign(size_t(outW) * visH, 0);
            for (int y = 0; y < visH; y++) {
                const int sy0 = y * lh / visH;
                const int sy1 = std::max(sy0 + 1, (y + 1) * lh / visH);
                for (int x = 0; x < visW; x++) {
                    const int sx0 = x * lw / visW;
                    const int sx1 = std::max(sx0 + 1, (x + 1) * lw / visW);
                    uint32_t r = 0, g = 0, b = 0, a = 0, n = 0;
                    for (int sy = sy0; sy < sy1; sy++) {
                        for (int sx = sx0; sx < sx1; sx++) {
                            const stbi_uc* px = data + (size_t(sy) * lw + sx) * 4;
                            r += px[0] * px[3] / 255;
                            g += px[1] * px[3] / 255;
                            b += px[2] * px[3] / 255;
                            a += px[3];
                            n++;
                        }
                    }
                    a /= n;
                    if (a >= 128) {
                        r = std::min(255u, r / n * 255 / a);
                        g = std::min(255u, g / n * 255 / a);
                        b = std::min(255u, b / n * 255 / a);
                        logo.texels[size_t(y) * outW + x] =
                            uint16_t(((r >> 3) << 11) | ((g >> 3) << 6) | ((b >> 3) << 1) | 1);
                    }
                }
            }
            stbi_image_free(data);
            printf("[SNAP-MENU] recomp_logo.png staged at %dx%d\n", logo.w, logo.h);
        }
    }

    uint32_t cursor = PixelsAddr;
    write_u32(DirectoryAddr + 0x4, StringCount);

    for (uint32_t id = 0; id < StringCount; id++) {
        int w, h;
        Strip strip;
        if (id == 0) {
            // The backdrop: a solid black tile the patch stretches over the
            // whole screen under the page.
            w = 16;
            h = 16;
        }
        else if (id == BaseCount + 22) {
            // The wordmark, staged even when absent: a zero width tells the
            // patch there is nothing to draw.
            w = logo.w;
            h = logo.h;
        }
        else if (id >= BaseCount + 18) {
            // Second-wave setting descriptions.
            strip = compose_lines(extraDescs[id - BaseCount - 18][0], extraDescs[id - BaseCount - 18][1]);
            w = strip.width;
            h = strip.height;
        }
        else if (id >= BaseCount + 9) {
            // Second-wave labels and values.
            strip = compose(extraStrings[id - BaseCount - 9]);
            w = strip.width;
            h = strip.height;
        }
        else if (id >= BaseCount + 8) {
            // The page heading, in the header face.
            strip = compose_hdr("Graphics");
            w = strip.width;
            h = strip.height;
        }
        else if (id >= BaseCount) {
            // A two-line setting description for the help box.
            strip = compose_lines(descs[id - BaseCount][0], descs[id - BaseCount][1]);
            w = strip.width;
            h = strip.height;
        }
        else if ((overrideNames[id] != nullptr) && load_override(overrideNames[id], strip)) {
            // A hand-made image takes the string's place.
            w = strip.width;
            h = strip.height;
        }
        else {
            strip = compose(strings[id]);
            if (id == STR_ITEM_LABEL_ID) {
                // The list item carries the stock items' bullet dot, taken
                // from the original sprite, at the original spacing.
                strip = add_item_dot(strip);
            }
            w = strip.width;
            h = strip.height;
        }

        write_u32(DirectoryAddr + 0x8 + id * 8, cursor);
        write_u16(DirectoryAddr + 0xC + id * 8, uint16_t(w));
        write_u16(DirectoryAddr + 0xE + id * 8, uint16_t(h));

        // Written as contiguous 64-texel column blocks, because the sprite
        // library loads each bitmap with a block load that cannot stride
        // through a wider image. Chunk k covers columns [64k, 64k+cw).
        const int chunks = (w + 63) / 64;
        uint32_t at = cursor;
        for (int k = 0; k < chunks; k++) {
            const int cx = k * 64;
            const int cw = std::min(64, w - cx);
            for (int y = 0; y < h; y++) {
                for (int x = 0; x < cw; x++) {
                    uint16_t texel;
                    if (id == 0) {
                        texel = 0x00FF;   // black, opaque
                    }
                    else if (id == BaseCount + 22) {
                        texel = logo.texels[size_t(y) * w + (cx + x)];   // RGBA16
                    }
                    else {
                        const size_t src = size_t(y) * w + (cx + x);
                        texel = uint16_t((strip.intensity[src] << 8) | strip.alpha[src]);
                    }
                    write_u16(at + uint32_t((y * cw + x) * 2), texel);
                }
            }
            at += uint32_t(cw * h * 2);
        }
        cursor = at;
        cursor = (cursor + 7u) & ~7u;
    }

    write_u32(DirectoryAddr + 0x0, DirectoryMagic);
    seed_mailbox();
    g_staged = true;
    printf("[SNAP-MENU] staged %u interface strings (%u bytes) for the graphics page\n",
        StringCount, cursor - PixelsAddr);
}

// Called every game tick. Applies and saves whatever the GRAPHICS page
// published since the last look -- the same live path the hotkeys use.
void poll_menu_mailbox(uint8_t* rdram) {
    if ((rdram == nullptr) || !g_staged) {
        return;
    }
    g_menu_rdram = rdram;
    if (read_u32_mail(MailboxAddr) != MailboxMagic) {
        return;
    }
    const uint32_t seq = read_u32_mail(MailboxAddr + 0x4);
    if (seq == g_last_applied_seq) {
        return;
    }
    g_last_applied_seq = seq;

    Settings &s = settings();
    s.resolution_scale = std::min<int>(read_u8_mail(MailboxAddr + 0x8), 8);
    const uint8_t msaaIndex = read_u8_mail(MailboxAddr + 0x9);
    s.msaa = (msaaIndex >= 3) ? 8 : (msaaIndex == 2) ? 4 : (msaaIndex == 1) ? 2 : 0;
    s.widescreen = read_u8_mail(MailboxAddr + 0xA) != 0;
    s.fps_mode = (read_u8_mail(MailboxAddr + 0xB) != 0) ? 1 : 0;
    s.upscale_2d = std::min<int>(read_u8_mail(MailboxAddr + 0xC), 2);
    s.present_filter = std::min<int>(read_u8_mail(MailboxAddr + 0xD), 2);
    s.dither_noise = read_u8_mail(MailboxAddr + 0xE) != 0;
    s.fullscreen = read_u8_mail(MailboxAddr + 0xF) != 0;
    s.downsample = int(read_u8_mail(MailboxAddr + 0x10)) + 1;
    s.three_point_filtering = read_u8_mail(MailboxAddr + 0x11) == 0;
    s.color_depth = std::min<int>(read_u8_mail(MailboxAddr + 0x12), 2);
    s.triple_buffering = read_u8_mail(MailboxAddr + 0x13) != 0;

    apply_graphics_settings();
    save_settings();
}

} // namespace snap
